version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: 'kafka'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092 # Change to 'kafka' which is the service name
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  tei2json-api:
    image: shenukacj/tei2json-api:0.0.5
    container_name: 'tei2json-api'
    ports:
      - '3001:3001'
    depends_on:
      - 'kafka'
    privileged: true
  
  tei-api:
    image: shenukacj/tei-api:0.0.1
    container_name: 'tei-api'
    ports:
      - '3000:3000'
    depends_on:
      - 'kafka'