version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-dev:
    image: 'bitnami/kafka:latest'
    container_name: 'kafka-dev'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

# sudo docker exec -it kafka-dev kafka-topics.sh --create --topic collections-topic --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1

# sudo docker exec -it kafka-dev kafka-topics.sh --list --bootstrap-server localhost:9092

# sudo docker exec -it kafka-dev kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic collections-topic --from-beginning

# sudo docker exec -it kafka-dev kafka-topics.sh --create --topic tei-topic --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 && sudo docker exec -it kafka-dev kafka-topics.sh --create --topic json-topic --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 && sudo docker exec -it kafka-dev kafka-topics.sh --create --topic collections-topic --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 

# kubectl exec -it kafka-7756d6c55d-4x94d -- kafka-topics.sh --create --topic tei-topic --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 && kubectl exec -it kafka-7756d6c55d-4x94d -- kafka-topics.sh --create --topic json-topic --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 && kubectl exec -it kafka-7756d6c55d-4x94d -- kafka-topics.sh --create --topic collections-topic --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 && kubectl exec -it kafka-7756d6c55d-4x94d -- kafka-topics.sh --create --topic tei-template-topic --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1

# kubectl exec -it kafka-7756d6c55d-4x94d -- kafka-topics.sh --list --bootstrap-server localhost:9092

# kubectl exec -it ksqldb-cli-847fbfcc9c-4r4km -- ksql http://ksqldb-server:8088

# kubectl exec -it tei2json-api-778bcf56d6-25g75 -- docker run shenukacj/cudl-xslt:0.0.5 && kubectl exec -it tei2json-api-778bcf56d6-25g75 -- node app.js